name: tekspogs
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  go_router: ^15.1.1
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2
  crypto: ^3.0.6
  get_it: ^8.0.3
  countup: ^0.1.4
  lottie: ^3.3.1
  syncfusion_flutter_charts: ^29.2.4
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:


  uses-material-design: true

  
  assets:
    - assets/app/
    - assets/app/game_mode/
    - assets/app/game_results/
    - assets/images/chips/
    - assets/images/betting_chips/
    - assets/images/
    - assets/images/pogs/
    - assets/images/banner/
    - assets/images/user/
    - assets/images/pogs/rarity/
    - assets/images/elements/
    - assets/results/
    - assets/bet_dialog/
    - assets/lottie/
    - assets/timer/
    - assets/images/game_mode/

    

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
        - asset: assets/fonts/poppins/Poppins-Italic.otf
          style: italic
    - family: Geologica
      fonts:
        - asset: assets/fonts/Geologica/static/Geologica_Auto-Regular.ttf
